### ISSUE TITLE
Proporcionar un enllaç de baixada

### ISSUE THREAD

**Issue by jmontane** [Softcatala/recull-de-termes#1]
Podem proporcionar un enllaç de baixa de l'última versió del recull, en format htm estaria bé?

**Comment by jordimas** [comment]
Hi ha una còpia a: https://www.softcatala.org/pub/softcatala/recull/recull.htm

**Comment by jmontane** [comment]
Perfecte, amb aquesta còpia ja fem. Gràcies.
